### ISSUE TITLE
Example of a GPU Job Pod ? 

### ISSUE THREAD

**Issue by Mistobaan** [openai/kubernetes-ec2-autoscaler#8]
How do you specify a pod that has # of GPUs as requirements? I checked in the test/data examples but none of those have gpu as resource.

**Comment by styk-tv** [comment]
Problem is that Kubernetes is by default not allowing access to GPU devices. They are talking about it for over a year now. Writing up proposals, recommendations and plans. https://github.com/kubernetes/kubernetes/issues/19049 and https://github.com/kubernetes/kubernetes/issues/17035 This is so frustrating that Nvidia decided to have their own Docker clone especially for that purpose https://github.com/NVIDIA/nvidia-docker Also Mesosphere DCOS supports GPUs out of the box. A LOT of people especially from Deep Learning environments abandoned K8S because of lack of GPU direction. Seems silly,

**Comment by tbchj** [comment]
k8s based on docker, not nvidia-docker. i use docker run on cpu, and use nvidia-docker run on gpu. but how to use the same way to run both gpu and cpu.
i also want a example to slove my problem

**Comment by r4j4h** [comment]
@styk-tv All great points, but to be clear, DC/OS had no issue because it runs binaries, not containers, by default.

@tbchj Please ask in the appropriate place then. Until upstream provides in 1.6 then what can be done here? https://github.com/kubernetes/kubernetes/issues/40998 https://github.com/kubernetes/kubernetes/issues/17035 Once it's in, you will use it here like you use it elsewhere in 1.6...which means probably not at all here because that's a pod-level concern not a node-level concern. Assuming your ASGs provide GPU enabled instances, if a pod can't be scheduled because of a lack of GPUs then it should scale up so it finds one.

How well that will work we won't know until we get there! :D but at least it's getting closer..

**Comment by ahundt** [comment]
gpu support has been merged to kubernetes master https://github.com/kubernetes/kubernetes/pull/42116
